### ISSUE TITLE
Hi not working I get this code

### ISSUE THREAD

**Issue by Tolithe** [yu7777/Auto-Advance--Anki_addon-#1]
Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Auto Advance automatically show answer  flip card  audio play repeat  speed⁩':
⁨Traceback (most recent call last):
  File "aqt\addons.py", line 211, in loadAddons
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\1747534155\__init__.py", line 1, in <module>
    from . import Auto_Advance
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\1747534155\Auto_Advance.py", line 26, in <module>
    from anki.sound import mplayerQueue, mplayerClear, mplayerEvt
ImportError:

**Comment by charlie090** [comment]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.29 (bbff62bf) Python 3.8.0 Qt 5.15.0 PyQt 5.15.0
Platform: Mac 10.15.6
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-08-07 23:28:46
Add-ons possibly involved: ⁨Auto Advance automatically show answer  flip card  audio play repeat  speed⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/charles.lee/Library/Application Support/Anki2/addons21/1747534155/Auto_Advance.py", line 343, in setupSound
    anki.sound.setupMPV()
AttributeError: module 'anki.sound' has no attribute 'setupMPV'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt/webview.py", line 37, in cmd
  File "aqt/webview.py", line 123, in _onCmd
  File "aqt/webview.py", line 544, in _onBridgeCmd
  File "aqt/overview.py", line 67, in _linkHandler
  File "aqt/main.py", line 646, in moveToState
  File "aqt/main.py", line 668, in _reviewState
  File "aqt/reviewer.py", line 65, in show
  File "aqt/reviewer.py", line 118, in nextCard
  File "aqt/reviewer.py", line 204, in _showQuestion
  File "aqt/gui_hooks.py", line 2026, in __call__
  File "anki/hooks.py", line 583, in runHook
  File "/Users/charles.lee/Library/Application Support/Anki2/addons21/1747534155/Auto_Advance.py", line 440, in show_question
    load_audio_to_player(Config.playlist_question)
  File "/Users/charles.lee/Library/Application Support/Anki2/addons21/1747534155/Auto_Advance.py", line 315, in load_audio_to_player
    setupSound()
  File "/Users/charles.lee/Library/Application Support/Anki2/addons21/1747534155/Auto_Advance.py", line 347, in setupSound
    except anki.mpv.MPVProcessError:
AttributeError: module 'anki' has no attribute 'mpv'
